name: Install Pandoc in GitHub Actions

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc

      - name: Verify Pandoc Installation
        run: |
          pandoc --version
